/* 
 * Reepay API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CardGatewayAgreement
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CardGatewayAgreementTests
    {
        // TODO uncomment below to declare an instance variable for CardGatewayAgreement
        //private CardGatewayAgreement instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CardGatewayAgreement
            //instance = new CardGatewayAgreement();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CardGatewayAgreement
        /// </summary>
        [Test]
        public void CardGatewayAgreementInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CardGatewayAgreement
            //Assert.IsInstanceOfType<CardGatewayAgreement> (instance, "variable 'instance' is a CardGatewayAgreement");
        }

        /// <summary>
        /// Test the property 'Provider'
        /// </summary>
        [Test]
        public void ProviderTest()
        {
            // TODO unit test for the property 'Provider'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'CardTypes'
        /// </summary>
        [Test]
        public void CardTypesTest()
        {
            // TODO unit test for the property 'CardTypes'
        }
        /// <summary>
        /// Test the property 'ProviderSettings'
        /// </summary>
        [Test]
        public void ProviderSettingsTest()
        {
            // TODO unit test for the property 'ProviderSettings'
        }
        /// <summary>
        /// Test the property 'GwRef'
        /// </summary>
        [Test]
        public void GwRefTest()
        {
            // TODO unit test for the property 'GwRef'
        }

    }

}
