/* 
 * Reepay API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CreateCoupon
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateCouponTests
    {
        // TODO uncomment below to declare an instance variable for CreateCoupon
        //private CreateCoupon instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateCoupon
            //instance = new CreateCoupon();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateCoupon
        /// </summary>
        [Test]
        public void CreateCouponInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateCoupon
            //Assert.IsInstanceOfType<CreateCoupon> (instance, "variable 'instance' is a CreateCoupon");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Handle'
        /// </summary>
        [Test]
        public void HandleTest()
        {
            // TODO unit test for the property 'Handle'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Discount'
        /// </summary>
        [Test]
        public void DiscountTest()
        {
            // TODO unit test for the property 'Discount'
        }
        /// <summary>
        /// Test the property 'AllPlans'
        /// </summary>
        [Test]
        public void AllPlansTest()
        {
            // TODO unit test for the property 'AllPlans'
        }
        /// <summary>
        /// Test the property 'EligiblePlans'
        /// </summary>
        [Test]
        public void EligiblePlansTest()
        {
            // TODO unit test for the property 'EligiblePlans'
        }
        /// <summary>
        /// Test the property 'MaxRedemptions'
        /// </summary>
        [Test]
        public void MaxRedemptionsTest()
        {
            // TODO unit test for the property 'MaxRedemptions'
        }
        /// <summary>
        /// Test the property 'ValidUntil'
        /// </summary>
        [Test]
        public void ValidUntilTest()
        {
            // TODO unit test for the property 'ValidUntil'
        }

    }

}
