/* 
 * Reepay API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UpdateSubscriptionPlan
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UpdateSubscriptionPlanTests
    {
        // TODO uncomment below to declare an instance variable for UpdateSubscriptionPlan
        //private UpdateSubscriptionPlan instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UpdateSubscriptionPlan
            //instance = new UpdateSubscriptionPlan();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdateSubscriptionPlan
        /// </summary>
        [Test]
        public void UpdateSubscriptionPlanInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UpdateSubscriptionPlan
            //Assert.IsInstanceOfType<UpdateSubscriptionPlan> (instance, "variable 'instance' is a UpdateSubscriptionPlan");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Vat'
        /// </summary>
        [Test]
        public void VatTest()
        {
            // TODO unit test for the property 'Vat'
        }
        /// <summary>
        /// Test the property 'DunningPlan'
        /// </summary>
        [Test]
        public void DunningPlanTest()
        {
            // TODO unit test for the property 'DunningPlan'
        }
        /// <summary>
        /// Test the property 'RenewalReminderEmailDays'
        /// </summary>
        [Test]
        public void RenewalReminderEmailDaysTest()
        {
            // TODO unit test for the property 'RenewalReminderEmailDays'
        }
        /// <summary>
        /// Test the property 'TrialReminderEmailDays'
        /// </summary>
        [Test]
        public void TrialReminderEmailDaysTest()
        {
            // TODO unit test for the property 'TrialReminderEmailDays'
        }
        /// <summary>
        /// Test the property 'PartialPeriodHandling'
        /// </summary>
        [Test]
        public void PartialPeriodHandlingTest()
        {
            // TODO unit test for the property 'PartialPeriodHandling'
        }

    }

}
