/* 
 * Reepay API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ReepayApi.Model
{
    /// <summary>
    /// CardToken
    /// </summary>
    [DataContract]
    public partial class CardToken :  IEquatable<CardToken>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CardToken" /> class.
        /// </summary>
        [JsonConstructor]
        protected CardToken() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CardToken" /> class.
        /// </summary>
        /// <param name="_CardToken">Add card to customer by card token (required).</param>
        public CardToken(string _CardToken = null)
        {
            // to ensure "_CardToken" is required (not null)
            if (_CardToken == null)
            {
                throw new InvalidDataException("_CardToken is a required property for CardToken and cannot be null");
            }
            else
            {
                this._CardToken = _CardToken;
            }
        }
        
        /// <summary>
        /// Add card to customer by card token
        /// </summary>
        /// <value>Add card to customer by card token</value>
        [DataMember(Name="card_token", EmitDefaultValue=false)]
        public string _CardToken { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CardToken {\n");
            sb.Append("  _CardToken: ").Append(_CardToken).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as CardToken);
        }

        /// <summary>
        /// Returns true if CardToken instances are equal
        /// </summary>
        /// <param name="other">Instance of CardToken to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CardToken other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this._CardToken == other._CardToken ||
                    this._CardToken != null &&
                    this._CardToken.Equals(other._CardToken)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this._CardToken != null)
                    hash = hash * 59 + this._CardToken.GetHashCode();
                return hash;
            }
        }
    }

}
