/* 
 * Reepay API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ReepayApi.Model
{
    /// <summary>
    /// CardTransaction
    /// </summary>
    [DataContract]
    public partial class CardTransaction :  IEquatable<CardTransaction>
    {
        /// <summary>
        /// State of the transaction, one of the following: `pending`, `processing`, `settled`, `refunded`, `failed`, `cancelled`
        /// </summary>
        /// <value>State of the transaction, one of the following: `pending`, `processing`, `settled`, `refunded`, `failed`, `cancelled`</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StateEnum
        {
            
            /// <summary>
            /// Enum Pending for "pending"
            /// </summary>
            [EnumMember(Value = "pending")]
            Pending,
            
            /// <summary>
            /// Enum Processing for "processing"
            /// </summary>
            [EnumMember(Value = "processing")]
            Processing,
            
            /// <summary>
            /// Enum Settled for "settled"
            /// </summary>
            [EnumMember(Value = "settled")]
            Settled,
            
            /// <summary>
            /// Enum Refunded for "refunded"
            /// </summary>
            [EnumMember(Value = "refunded")]
            Refunded,
            
            /// <summary>
            /// Enum Failed for "failed"
            /// </summary>
            [EnumMember(Value = "failed")]
            Failed,
            
            /// <summary>
            /// Enum Cancelled for "cancelled"
            /// </summary>
            [EnumMember(Value = "cancelled")]
            Cancelled
        }

        /// <summary>
        /// Transaction type, one of the following: 'settle', 'refund'
        /// </summary>
        /// <value>Transaction type, one of the following: 'settle', 'refund'</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum Settle for "settle"
            /// </summary>
            [EnumMember(Value = "settle")]
            Settle,
            
            /// <summary>
            /// Enum Refund for "refund"
            /// </summary>
            [EnumMember(Value = "refund")]
            Refund
        }

        /// <summary>
        /// State of the transaction, one of the following: `pending`, `processing`, `settled`, `refunded`, `failed`, `cancelled`
        /// </summary>
        /// <value>State of the transaction, one of the following: `pending`, `processing`, `settled`, `refunded`, `failed`, `cancelled`</value>
        [DataMember(Name="state", EmitDefaultValue=false)]
        public StateEnum? State { get; set; }
        /// <summary>
        /// Transaction type, one of the following: 'settle', 'refund'
        /// </summary>
        /// <value>Transaction type, one of the following: 'settle', 'refund'</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public TypeEnum? Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CardTransaction" /> class.
        /// </summary>
        [JsonConstructor]
        protected CardTransaction() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CardTransaction" /> class.
        /// </summary>
        /// <param name="Settled">When the transaction was settled, in [ISO-8601](http://en.wikipedia.org/wiki/ISO_8601) extended offset date-time format. (required).</param>
        /// <param name="Failed">When the transaction failed, in [ISO-8601](http://en.wikipedia.org/wiki/ISO_8601) extended offset date-time format. (required).</param>
        /// <param name="Refunded">When the transaction was refunded, in [ISO-8601](http://en.wikipedia.org/wiki/ISO_8601) extended offset date-time format. (required).</param>
        /// <param name="Card">Card used for transaction (required).</param>
        /// <param name="Error">Error code if failed.</param>
        /// <param name="RefTransaction">Id of a possible referenced transaction.</param>
        /// <param name="GwId">Gateway id for card.</param>
        /// <param name="LastFailed">When the card transaction last failed, in [ISO-8601](http://en.wikipedia.org/wiki/ISO_8601) extended offset date-time format..</param>
        /// <param name="FirstFailed">When the card transaction first failed, in [ISO-8601](http://en.wikipedia.org/wiki/ISO_8601) extended offset date-time format..</param>
        public CardTransaction(DateTime? Settled = null, DateTime? Failed = null, DateTime? Refunded = null, Card Card = null, string Error = null, string RefTransaction = null, string GwId = null, DateTime? LastFailed = null, DateTime? FirstFailed = null)
        {
            // to ensure "Settled" is required (not null)
            if (Settled == null)
            {
                throw new InvalidDataException("Settled is a required property for CardTransaction and cannot be null");
            }
            else
            {
                this.Settled = Settled;
            }
            // to ensure "Failed" is required (not null)
            if (Failed == null)
            {
                throw new InvalidDataException("Failed is a required property for CardTransaction and cannot be null");
            }
            else
            {
                this.Failed = Failed;
            }
            // to ensure "Refunded" is required (not null)
            if (Refunded == null)
            {
                throw new InvalidDataException("Refunded is a required property for CardTransaction and cannot be null");
            }
            else
            {
                this.Refunded = Refunded;
            }
            // to ensure "Card" is required (not null)
            if (Card == null)
            {
                throw new InvalidDataException("Card is a required property for CardTransaction and cannot be null");
            }
            else
            {
                this.Card = Card;
            }
            this.Error = Error;
            this.RefTransaction = RefTransaction;
            this.GwId = GwId;
            this.LastFailed = LastFailed;
            this.FirstFailed = FirstFailed;
        }
        
        /// <summary>
        /// Transaction id assigned by Reepay
        /// </summary>
        /// <value>Transaction id assigned by Reepay</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; private set; }
        /// <summary>
        /// Invoice id
        /// </summary>
        /// <value>Invoice id</value>
        [DataMember(Name="invoice", EmitDefaultValue=false)]
        public string Invoice { get; private set; }
        /// <summary>
        /// The transaction amount
        /// </summary>
        /// <value>The transaction amount</value>
        [DataMember(Name="amount", EmitDefaultValue=false)]
        public int? Amount { get; private set; }
        /// <summary>
        /// When the transaction was settled, in [ISO-8601](http://en.wikipedia.org/wiki/ISO_8601) extended offset date-time format.
        /// </summary>
        /// <value>When the transaction was settled, in [ISO-8601](http://en.wikipedia.org/wiki/ISO_8601) extended offset date-time format.</value>
        [DataMember(Name="settled", EmitDefaultValue=false)]
        public DateTime? Settled { get; set; }
        /// <summary>
        /// When the transaction failed, in [ISO-8601](http://en.wikipedia.org/wiki/ISO_8601) extended offset date-time format.
        /// </summary>
        /// <value>When the transaction failed, in [ISO-8601](http://en.wikipedia.org/wiki/ISO_8601) extended offset date-time format.</value>
        [DataMember(Name="failed", EmitDefaultValue=false)]
        public DateTime? Failed { get; set; }
        /// <summary>
        /// When the transaction was refunded, in [ISO-8601](http://en.wikipedia.org/wiki/ISO_8601) extended offset date-time format.
        /// </summary>
        /// <value>When the transaction was refunded, in [ISO-8601](http://en.wikipedia.org/wiki/ISO_8601) extended offset date-time format.</value>
        [DataMember(Name="refunded", EmitDefaultValue=false)]
        public DateTime? Refunded { get; set; }
        /// <summary>
        /// Date when the transaction was created. In [ISO-8601](http://en.wikipedia.org/wiki/ISO_8601) extended offset date-time format.
        /// </summary>
        /// <value>Date when the transaction was created. In [ISO-8601](http://en.wikipedia.org/wiki/ISO_8601) extended offset date-time format.</value>
        [DataMember(Name="created", EmitDefaultValue=false)]
        public DateTime? Created { get; private set; }
        /// <summary>
        /// Card used for transaction
        /// </summary>
        /// <value>Card used for transaction</value>
        [DataMember(Name="card", EmitDefaultValue=false)]
        public Card Card { get; set; }
        /// <summary>
        /// Error code if failed
        /// </summary>
        /// <value>Error code if failed</value>
        [DataMember(Name="error", EmitDefaultValue=false)]
        public string Error { get; set; }
        /// <summary>
        /// Id of a possible referenced transaction
        /// </summary>
        /// <value>Id of a possible referenced transaction</value>
        [DataMember(Name="ref_transaction", EmitDefaultValue=false)]
        public string RefTransaction { get; set; }
        /// <summary>
        /// Gateway id for card
        /// </summary>
        /// <value>Gateway id for card</value>
        [DataMember(Name="gw_id", EmitDefaultValue=false)]
        public string GwId { get; set; }
        /// <summary>
        /// When the card transaction last failed, in [ISO-8601](http://en.wikipedia.org/wiki/ISO_8601) extended offset date-time format.
        /// </summary>
        /// <value>When the card transaction last failed, in [ISO-8601](http://en.wikipedia.org/wiki/ISO_8601) extended offset date-time format.</value>
        [DataMember(Name="last_failed", EmitDefaultValue=false)]
        public DateTime? LastFailed { get; set; }
        /// <summary>
        /// When the card transaction first failed, in [ISO-8601](http://en.wikipedia.org/wiki/ISO_8601) extended offset date-time format.
        /// </summary>
        /// <value>When the card transaction first failed, in [ISO-8601](http://en.wikipedia.org/wiki/ISO_8601) extended offset date-time format.</value>
        [DataMember(Name="first_failed", EmitDefaultValue=false)]
        public DateTime? FirstFailed { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CardTransaction {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  Invoice: ").Append(Invoice).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Settled: ").Append(Settled).Append("\n");
            sb.Append("  Failed: ").Append(Failed).Append("\n");
            sb.Append("  Refunded: ").Append(Refunded).Append("\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  Card: ").Append(Card).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("  RefTransaction: ").Append(RefTransaction).Append("\n");
            sb.Append("  GwId: ").Append(GwId).Append("\n");
            sb.Append("  LastFailed: ").Append(LastFailed).Append("\n");
            sb.Append("  FirstFailed: ").Append(FirstFailed).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as CardTransaction);
        }

        /// <summary>
        /// Returns true if CardTransaction instances are equal
        /// </summary>
        /// <param name="other">Instance of CardTransaction to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CardTransaction other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Id == other.Id ||
                    this.Id != null &&
                    this.Id.Equals(other.Id)
                ) && 
                (
                    this.State == other.State ||
                    this.State != null &&
                    this.State.Equals(other.State)
                ) && 
                (
                    this.Invoice == other.Invoice ||
                    this.Invoice != null &&
                    this.Invoice.Equals(other.Invoice)
                ) && 
                (
                    this.Type == other.Type ||
                    this.Type != null &&
                    this.Type.Equals(other.Type)
                ) && 
                (
                    this.Amount == other.Amount ||
                    this.Amount != null &&
                    this.Amount.Equals(other.Amount)
                ) && 
                (
                    this.Settled == other.Settled ||
                    this.Settled != null &&
                    this.Settled.Equals(other.Settled)
                ) && 
                (
                    this.Failed == other.Failed ||
                    this.Failed != null &&
                    this.Failed.Equals(other.Failed)
                ) && 
                (
                    this.Refunded == other.Refunded ||
                    this.Refunded != null &&
                    this.Refunded.Equals(other.Refunded)
                ) && 
                (
                    this.Created == other.Created ||
                    this.Created != null &&
                    this.Created.Equals(other.Created)
                ) && 
                (
                    this.Card == other.Card ||
                    this.Card != null &&
                    this.Card.Equals(other.Card)
                ) && 
                (
                    this.Error == other.Error ||
                    this.Error != null &&
                    this.Error.Equals(other.Error)
                ) && 
                (
                    this.RefTransaction == other.RefTransaction ||
                    this.RefTransaction != null &&
                    this.RefTransaction.Equals(other.RefTransaction)
                ) && 
                (
                    this.GwId == other.GwId ||
                    this.GwId != null &&
                    this.GwId.Equals(other.GwId)
                ) && 
                (
                    this.LastFailed == other.LastFailed ||
                    this.LastFailed != null &&
                    this.LastFailed.Equals(other.LastFailed)
                ) && 
                (
                    this.FirstFailed == other.FirstFailed ||
                    this.FirstFailed != null &&
                    this.FirstFailed.Equals(other.FirstFailed)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Id != null)
                    hash = hash * 59 + this.Id.GetHashCode();
                if (this.State != null)
                    hash = hash * 59 + this.State.GetHashCode();
                if (this.Invoice != null)
                    hash = hash * 59 + this.Invoice.GetHashCode();
                if (this.Type != null)
                    hash = hash * 59 + this.Type.GetHashCode();
                if (this.Amount != null)
                    hash = hash * 59 + this.Amount.GetHashCode();
                if (this.Settled != null)
                    hash = hash * 59 + this.Settled.GetHashCode();
                if (this.Failed != null)
                    hash = hash * 59 + this.Failed.GetHashCode();
                if (this.Refunded != null)
                    hash = hash * 59 + this.Refunded.GetHashCode();
                if (this.Created != null)
                    hash = hash * 59 + this.Created.GetHashCode();
                if (this.Card != null)
                    hash = hash * 59 + this.Card.GetHashCode();
                if (this.Error != null)
                    hash = hash * 59 + this.Error.GetHashCode();
                if (this.RefTransaction != null)
                    hash = hash * 59 + this.RefTransaction.GetHashCode();
                if (this.GwId != null)
                    hash = hash * 59 + this.GwId.GetHashCode();
                if (this.LastFailed != null)
                    hash = hash * 59 + this.LastFailed.GetHashCode();
                if (this.FirstFailed != null)
                    hash = hash * 59 + this.FirstFailed.GetHashCode();
                return hash;
            }
        }
    }

}
