/* 
 * Reepay API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ReepayApi.Model
{
    /// <summary>
    /// CreditNoteLine
    /// </summary>
    [DataContract]
    public partial class CreditNoteLine :  IEquatable<CreditNoteLine>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreditNoteLine" /> class.
        /// </summary>
        [JsonConstructor]
        public CreditNoteLine()
        {
        }
        
        /// <summary>
        /// Credit note line total amount
        /// </summary>
        /// <value>Credit note line total amount</value>
        [DataMember(Name="amount", EmitDefaultValue=false)]
        public int? Amount { get; private set; }
        /// <summary>
        /// Credit note line text
        /// </summary>
        /// <value>Credit note line text</value>
        [DataMember(Name="text", EmitDefaultValue=false)]
        public string Text { get; private set; }
        /// <summary>
        /// Credit note line quantity
        /// </summary>
        /// <value>Credit note line quantity</value>
        [DataMember(Name="quantity", EmitDefaultValue=false)]
        public int? Quantity { get; private set; }
        /// <summary>
        /// Reference to invoice orderline this credit note line relates to
        /// </summary>
        /// <value>Reference to invoice orderline this credit note line relates to</value>
        [DataMember(Name="order_line_id", EmitDefaultValue=false)]
        public string OrderLineId { get; private set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreditNoteLine {\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  OrderLineId: ").Append(OrderLineId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as CreditNoteLine);
        }

        /// <summary>
        /// Returns true if CreditNoteLine instances are equal
        /// </summary>
        /// <param name="other">Instance of CreditNoteLine to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreditNoteLine other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Amount == other.Amount ||
                    this.Amount != null &&
                    this.Amount.Equals(other.Amount)
                ) && 
                (
                    this.Text == other.Text ||
                    this.Text != null &&
                    this.Text.Equals(other.Text)
                ) && 
                (
                    this.Quantity == other.Quantity ||
                    this.Quantity != null &&
                    this.Quantity.Equals(other.Quantity)
                ) && 
                (
                    this.OrderLineId == other.OrderLineId ||
                    this.OrderLineId != null &&
                    this.OrderLineId.Equals(other.OrderLineId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Amount != null)
                    hash = hash * 59 + this.Amount.GetHashCode();
                if (this.Text != null)
                    hash = hash * 59 + this.Text.GetHashCode();
                if (this.Quantity != null)
                    hash = hash * 59 + this.Quantity.GetHashCode();
                if (this.OrderLineId != null)
                    hash = hash * 59 + this.OrderLineId.GetHashCode();
                return hash;
            }
        }
    }

}
