/* 
 * Reepay API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ReepayApi.Model
{
    /// <summary>
    /// MailSettings
    /// </summary>
    [DataContract]
    public partial class MailSettings :  IEquatable<MailSettings>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MailSettings" /> class.
        /// </summary>
        [JsonConstructor]
        protected MailSettings() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MailSettings" /> class.
        /// </summary>
        /// <param name="Bcc">Optional Bcc email address to use for all mails. Rfc 822 address..</param>
        /// <param name="ReplyTo">Optional Reply-To email address. Rfc 822 address..</param>
        public MailSettings(string Bcc = null, string ReplyTo = null)
        {
            this.Bcc = Bcc;
            this.ReplyTo = ReplyTo;
        }
        
        /// <summary>
        /// Optional Bcc email address to use for all mails. Rfc 822 address.
        /// </summary>
        /// <value>Optional Bcc email address to use for all mails. Rfc 822 address.</value>
        [DataMember(Name="bcc", EmitDefaultValue=false)]
        public string Bcc { get; set; }
        /// <summary>
        /// Default email sender address. Rfc 822 address.
        /// </summary>
        /// <value>Default email sender address. Rfc 822 address.</value>
        [DataMember(Name="default_from", EmitDefaultValue=false)]
        public string DefaultFrom { get; private set; }
        /// <summary>
        /// Optional Reply-To email address. Rfc 822 address.
        /// </summary>
        /// <value>Optional Reply-To email address. Rfc 822 address.</value>
        [DataMember(Name="reply_to", EmitDefaultValue=false)]
        public string ReplyTo { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MailSettings {\n");
            sb.Append("  Bcc: ").Append(Bcc).Append("\n");
            sb.Append("  DefaultFrom: ").Append(DefaultFrom).Append("\n");
            sb.Append("  ReplyTo: ").Append(ReplyTo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as MailSettings);
        }

        /// <summary>
        /// Returns true if MailSettings instances are equal
        /// </summary>
        /// <param name="other">Instance of MailSettings to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MailSettings other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Bcc == other.Bcc ||
                    this.Bcc != null &&
                    this.Bcc.Equals(other.Bcc)
                ) && 
                (
                    this.DefaultFrom == other.DefaultFrom ||
                    this.DefaultFrom != null &&
                    this.DefaultFrom.Equals(other.DefaultFrom)
                ) && 
                (
                    this.ReplyTo == other.ReplyTo ||
                    this.ReplyTo != null &&
                    this.ReplyTo.Equals(other.ReplyTo)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Bcc != null)
                    hash = hash * 59 + this.Bcc.GetHashCode();
                if (this.DefaultFrom != null)
                    hash = hash * 59 + this.DefaultFrom.GetHashCode();
                if (this.ReplyTo != null)
                    hash = hash * 59 + this.ReplyTo.GetHashCode();
                return hash;
            }
        }
    }

}
