/* 
 * Reepay API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ReepayApi.Model
{
    /// <summary>
    /// UpdateCardGatewayAgreement
    /// </summary>
    [DataContract]
    public partial class UpdateCardGatewayAgreement :  IEquatable<UpdateCardGatewayAgreement>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateCardGatewayAgreement" /> class.
        /// </summary>
        [JsonConstructor]
        protected UpdateCardGatewayAgreement() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateCardGatewayAgreement" /> class.
        /// </summary>
        /// <param name="CardTypes">Card types supported by agreement (required).</param>
        /// <param name="ProviderSettings">Key value map of provider settings.</param>
        public UpdateCardGatewayAgreement(List<string> CardTypes = null, Dictionary<string, Object> ProviderSettings = null)
        {
            // to ensure "CardTypes" is required (not null)
            if (CardTypes == null)
            {
                throw new InvalidDataException("CardTypes is a required property for UpdateCardGatewayAgreement and cannot be null");
            }
            else
            {
                this.CardTypes = CardTypes;
            }
            this.ProviderSettings = ProviderSettings;
        }
        
        /// <summary>
        /// Card types supported by agreement
        /// </summary>
        /// <value>Card types supported by agreement</value>
        [DataMember(Name="card_types", EmitDefaultValue=false)]
        public List<string> CardTypes { get; set; }
        /// <summary>
        /// Key value map of provider settings
        /// </summary>
        /// <value>Key value map of provider settings</value>
        [DataMember(Name="provider_settings", EmitDefaultValue=false)]
        public Dictionary<string, Object> ProviderSettings { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateCardGatewayAgreement {\n");
            sb.Append("  CardTypes: ").Append(CardTypes).Append("\n");
            sb.Append("  ProviderSettings: ").Append(ProviderSettings).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as UpdateCardGatewayAgreement);
        }

        /// <summary>
        /// Returns true if UpdateCardGatewayAgreement instances are equal
        /// </summary>
        /// <param name="other">Instance of UpdateCardGatewayAgreement to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateCardGatewayAgreement other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.CardTypes == other.CardTypes ||
                    this.CardTypes != null &&
                    this.CardTypes.SequenceEqual(other.CardTypes)
                ) && 
                (
                    this.ProviderSettings == other.ProviderSettings ||
                    this.ProviderSettings != null &&
                    this.ProviderSettings.SequenceEqual(other.ProviderSettings)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.CardTypes != null)
                    hash = hash * 59 + this.CardTypes.GetHashCode();
                if (this.ProviderSettings != null)
                    hash = hash * 59 + this.ProviderSettings.GetHashCode();
                return hash;
            }
        }
    }

}
