/* 
 * Reepay API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ReepayApi.Model
{
    /// <summary>
    /// UserRenew
    /// </summary>
    [DataContract]
    public partial class UserRenew :  IEquatable<UserRenew>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserRenew" /> class.
        /// </summary>
        [JsonConstructor]
        public UserRenew()
        {
        }
        
        /// <summary>
        /// Authentication token to use in X-Auth-Token
        /// </summary>
        /// <value>Authentication token to use in X-Auth-Token</value>
        [DataMember(Name="token", EmitDefaultValue=false)]
        public string Token { get; private set; }
        /// <summary>
        /// Token time-to-live in minutes
        /// </summary>
        /// <value>Token time-to-live in minutes</value>
        [DataMember(Name="token_ttl", EmitDefaultValue=false)]
        public int? TokenTtl { get; private set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UserRenew {\n");
            sb.Append("  Token: ").Append(Token).Append("\n");
            sb.Append("  TokenTtl: ").Append(TokenTtl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as UserRenew);
        }

        /// <summary>
        /// Returns true if UserRenew instances are equal
        /// </summary>
        /// <param name="other">Instance of UserRenew to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UserRenew other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Token == other.Token ||
                    this.Token != null &&
                    this.Token.Equals(other.Token)
                ) && 
                (
                    this.TokenTtl == other.TokenTtl ||
                    this.TokenTtl != null &&
                    this.TokenTtl.Equals(other.TokenTtl)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Token != null)
                    hash = hash * 59 + this.Token.GetHashCode();
                if (this.TokenTtl != null)
                    hash = hash * 59 + this.TokenTtl.GetHashCode();
                return hash;
            }
        }
    }

}
